name: Generate Android Keybox

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

jobs:
  build-keybox:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: Install Python modules
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Keybox generation pipeline
        run: |
          python generate.py

      - name: Prepare GitHub Pages root
        run: |
          mkdir -p site
          cp keybox.xml site/

      - name: Upload artifact to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build-keybox
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
